Fix forward a test failure in ag/27626837
The failure is:

com.android.healthfitness.flags.AconfigFlagHelperTest#phr_featureFlagFalseAndDbFlagFalse_expectFalse: FAILED (2ms)

STACKTRACE:
java.lang.IllegalAccessError: Field 'com.android.healthfitness.flags.AconfigFlagHelper.DB_VERSION_TO_DB_FLAG_MAP' is inaccessible to class 'com.android.healthfitness.flags.AconfigFlagHelperTest' (declaration of 'com.android.healthfitness.flags.AconfigFlagHelperTest' appears in /data/app/~~XTlg_zmKOgX1GvR9mSMwDA==/com.android.healthconnect.unittests-9ebU7gs7Me_DF7I6h3QjvQ==/base.apk)
        at com.android.healthfitness.flags.AconfigFlagHelperTest.setup(AconfigFlagHelperTest.java:42)

The fix is to make the field public instead of package private, see https://groups.google.com/a/google.com/g/android-chatty-eng/c/TymmRzs3UcY/m/_JeFcynRBwAJ

Test: atest
Bug: 340809376
Flag: EXEMPT test failure fix
Change-Id: I988aa6a31bfd089f238d3cfbcc5f4192bbaa7667