Remove empty test files which cause atest to fail
Currently, in `main` branch, there are empty test files which cause
`atest "CtsHealthFitnessDeviceTestCases:android.healthconnect.cts.backgroundread.BackgroundReadTest"` to fail with:

```
atest.test_finders.test_filter_utils.MissingPackageNameError: /usr/local/google/home/itsleo/AOSP/main/packages/modules/HealthFitness/tests/cts/src/android/healthconnect/cts/BasalMetabolicRateRecordTest.java: Test class java file does not contain a package name.
```

Those empty test files are probably a result of merges, there might be
more of them, we should remove them if they cause atest failures.

Test: N/A
Change-Id: I1293f14602e583afe56b5f1e0e623fff89c4e9d4